### ISSUE TITLE
Call to undefined method App\Models\Page::__set_state() 

### ISSUE THREAD

**Issue by HDVinnie** [elcobvg/laravel-opcache#14]
Uncaught BadMethodCallException: Call to undefined method App\Models\Page::__set_state() in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50 

```
Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException('__set_state') #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1614): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), '__set_state', Array) #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1626): Illuminate\Database\Eloquent\Model->__call('__set_state', Array) #3 /var/www/html/storage/framework/cache/data/unit3d-39b6f89872f56543cedea85d00a994d7150cbf29(6): Illuminate\Database\Eloquent\Model::__callStatic('__set_state', Array) #4 /var/www/html/vendor/elcobvg/laravel-opcache/src/Store.php(118): include('/var/www/html/s...') #5 /var/www/html/vend {"userId":3,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught BadMethodCallException: Call to undefined method App\\Models\\Page::__set_state() in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50 Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('__set_state') #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1614): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), '__set_state', Array) #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1626): Illuminate\\Database\\Eloquent\\Model->__call('__set_state', Array) #3 /var/www/html/storage/framework/cache/data/unit3d-39b6f89872f56543cedea85d00a994d7150cbf29(6): Illuminate\\Database\\Eloquent\\Model::__callStatic('__set_state', Array) #4 /var/www/html/vendor/elcobvg/laravel-opcache/src/Store.php(118): include('/var/www/html/s...') #5 /var/www/html/vend at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50) [stacktrace] #0 {main} "}
```

**Comment by elcobvg** [comment]
Did you base your model on the base model included in the package?

**Comment by HDVinnie** [comment]
Nope. Was late and overlooked that. My apologies and thanks.

**Comment by digitcreators** [comment]
Just remove project/bootstrap/cache/routes-7.php

and then run
1. php artisan optimize
2. php artisan config:clear
3. php artisan config:cache

**Comment by omidMolaverdi** [comment]
Thanks for the great work.

I have the same issue : `Call to undefined method App\User::__set_state()`

Here is my `User.php`
```

<?php

namespace App;

use App\Notifications\MailResetPasswordToken;
use Cmgmyr\Messenger\Models\Message;
use Cmgmyr\Messenger\Models\Participant;
use Cmgmyr\Messenger\Models\Thread;
use Cmgmyr\Messenger\Traits\Messagable;
use Eloquent;
use HighIdeas\UsersOnline\Traits\UsersOnlineTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Yadahan\AuthenticationLog\AuthenticationLogable;


class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use Messagable;
    use AuthenticationLogable;
    use UsersOnlineTrait;
...
}
```
